USE master
CREATE DATABASE Gateways
GO

USE [Gateways]
GO

/****** Object:  Table [dbo].[Gateway]    Script Date: 22/08/2020 20:05:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Gateway](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[SerialNumber] [NVARCHAR](MAX) NULL,
	[Human_Readable] [NVARCHAR](MAX) NULL,
	[Ipv4] [NVARCHAR](MAX) NULL,
 CONSTRAINT [PK_dbo.Gateway] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Peripheral](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[Uid] [INT] NOT NULL,
	[Vendor] [NVARCHAR](MAX) NULL,
	[CreatedDate] [DATETIME] NOT NULL,
	[Status] [BIT] NOT NULL,
	[GatewayEntity_Id] [INT] NULL,
 CONSTRAINT [PK_dbo.Peripheral] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Peripheral]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Peripheral_dbo.Gateway_GatewayEntity_Id] FOREIGN KEY([GatewayEntity_Id])
REFERENCES [dbo].[Gateway] ([Id])
GO

ALTER TABLE [dbo].[Peripheral] CHECK CONSTRAINT [FK_dbo.Peripheral_dbo.Gateway_GatewayEntity_Id]
GO